baseURL = "/"
languageCode = "en-us"
title = "Virtool"
theme = "virtool"
staticDir = ["static"]

enableGitInfo = true
pygmentsCodeFences = true

[sitemap]
  filename = "sitemap.xml"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[menu]
  [[menu.manual]]
    name = "Getting Started"
    weight = 10
    
  [[menu.manual]]
    name = "Tutorials"
    weight = 20

  [[menu.manual]]
    name = "User Guide"
    weight = 30

  [[menu.manual]]
    name = "Science"
    weight = 40

  [[menu.developer]]
    name = "Contributing"
    weight = 10

  [[menu.developer]]
    name = "API"
    weight = 20

  [[menu.developer]]
    name = "Backend"
    weight = 30

  [[menu.developer]]
    name = "Frontend"
    weight = 40
